require(['config'],function(){
    require(['jquery','banner','head'],function($){
        var bigbox = location.search.slice(1)
        console.log(bigbox);
        $.ajax({
            url:'../api/detail.php',
            dataType:'json',
            data:{
                id:bigbox
            },
            success:function(data){
                console.log(data);
                $('#goodsimg').attr('src','../'+data[0].imgurl.slice(2,-2));
                $('.goodsname').text(data[0].details);
                $('.price').text(data[0].goodsprice);
                $('#pro_view_more').text(data[0].category);
                $('.goodname').text(data[0].goodsname);
            }
        })
    })
});